### ISSUE TITLE
cannot import name 'get_last_week_content'

### ISSUE THREAD

**Issue by Giles2000** [CodingCrush/WeeklyReport#11]
docker 运行过程中报了一堆缺少运行依赖的包。补充requirements.txt文件内后报如下错误：

ImportError: cannot import name 'get_last_week_content'

这。。utils引入的有问题啊，需要高版本么？ 

建议requirements.txt里面的清单指定版本

**Comment by At0mn** [comment]
Flask==1.1.4
flask_bootstrap
flask_login
Flask-Script==2.0.6
Flask-WTF==0.14.3
Flask-Mail
flask-admin
WTForms==2.3.3
gunicorn
chartkick
flask_sqlalchemy
flask-migrate==2.5.3
flask_babelex
psycopg2

我自己一点一点改的 这个可以

**Comment by Giles2000** [comment]
> 

3q~
