### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-sg4cklnw/psycopg2/

### ISSUE THREAD

**Issue by x903** [CodingCrush/WeeklyReport#9]
我在部署的时候一直报这个错误，请问怎么解决呢

`[root@localhost WeeklyReport]# docker build -t weeklyreport:0.2 .
Sending build context to Docker daemon  48.49MB
Step 1/16 : FROM centos:7
 ---> 5e35e350aded
Step 2/16 : MAINTAINER CodingCrush
 ---> Using cache
 ---> 7f48056d2244
Step 3/16 : ENV LANG en_US.UTF-8
 ---> Using cache
 ---> 8071860d93f3
Step 4/16 : RUN ln -s -f /usr/share/zoneinfo/Asia/Shanghai /etc/localtime &&     curl -fsSL https://setup.ius.io/ | sh &&     yum update -y &&     yum install -y python36u python36u-devel python36u-pip &&     mkdir ~/.pip &&     echo -e "[global]\nindex-url=http://pypi.douban.com/simple/\ntrusted-host=pypi.douban.com">~/.pip/pip.conf &&     yum clean all
 ---> Using cache
 ---> 5a1e5ab969d7
Step 5/16 : RUN yum install -y supervisor
 ---> Using cache
 ---> 7dc748f7eb90
Step 6/16 : RUN mkdir -p /deploy
 ---> Using cache
 ---> ce1cf984ec87
Step 7/16 : WORKDIR /deploy
 ---> Using cache
 ---> 7e373e00d624
Step 8/16 : COPY requirements.txt /deploy/requirements.txt
 ---> Using cache
 ---> 5f616ea0a7bd
Step 9/16 : RUN pip3.6 install -r requirements.txt --timeout=120
 ---> Running in ba054833bd9e
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3.6 install --user` instead.
Collecting flask (from -r requirements.txt (line 1))
  Downloading http://pypi.doubanio.com/packages/9b/93/628509b8d5dc749656a9641f4caf13540e2cdec85276964ff8f43bbb1d3b/Flask-1.1.1-py2.py3-none-any.whl (94kB)
Collecting flask_bootstrap (from -r requirements.txt (line 2))
  Downloading http://pypi.doubanio.com/packages/88/53/958ce7c2aa26280b7fd7f3eecbf13053f1302ee2acb1db58ef32e1c23c2a/Flask-Bootstrap-3.3.7.1.tar.gz (456kB)
Collecting flask_login (from -r requirements.txt (line 3))
  Downloading http://pypi.doubanio.com/packages/c1/ff/bd9a4d2d81bf0c07d9e53e8cd3d675c56553719bbefd372df69bf1b3c1e4/Flask-Login-0.4.1.tar.gz
Collecting flask_script (from -r requirements.txt (line 4))
  Downloading http://pypi.doubanio.com/packages/00/a4/cd587b2b19f043b65bf33ceda2f6e4e6cdbd0ce18d01a52b9559781b1da6/Flask-Script-2.0.6.tar.gz (43kB)
Collecting flask_wtf (from -r requirements.txt (line 5))
  Downloading http://pypi.doubanio.com/packages/60/3a/58c629472d10539ae5167dc7c1fecfa95dd7d0b7864623931e3776438a24/Flask_WTF-0.14.2-py2.py3-none-any.whl
Collecting Flask-Mail (from -r requirements.txt (line 6))
  Downloading http://pypi.doubanio.com/packages/05/2f/6a545452040c2556559779db87148d2a85e78a26f90326647b51dc5e81e9/Flask-Mail-0.9.1.tar.gz (45kB)
Collecting flask-admin (from -r requirements.txt (line 7))
  Downloading http://pypi.doubanio.com/packages/03/4e/a92e3c5cee3fce68fda877b437ed4657df3a0168091f6d2cab6c94d932e3/Flask-Admin-1.5.4.tar.gz (1.7MB)
Collecting gunicorn (from -r requirements.txt (line 8))
  Downloading http://pypi.doubanio.com/packages/69/ca/926f7cd3a2014b16870086b2d0fdc84a9e49473c68a8dff8b57f7c156f43/gunicorn-20.0.4-py2.py3-none-any.whl (77kB)
Collecting chartkick (from -r requirements.txt (line 9))
  Downloading http://pypi.doubanio.com/packages/cc/ce/623769bffe0a4849e4008b52d17a2d4ef57d42eca96954e8593325670967/chartkick-0.5.0.tar.gz
Collecting flask_sqlalchemy (from -r requirements.txt (line 10))
  Downloading http://pypi.doubanio.com/packages/1e/65/226d95466c75e34e291a76890ed0e27af2e46ab913002847856f11d4d59d/Flask_SQLAlchemy-2.4.1-py2.py3-none-any.whl
Collecting flask_migrate (from -r requirements.txt (line 11))
  Downloading http://pypi.doubanio.com/packages/4b/22/d20a105f13c58fe590ef38ac59d5cabc1a917549ea8f90b0ca7b4e84f6be/Flask_Migrate-2.5.2-py2.py3-none-any.whl
Collecting flask_babelex (from -r requirements.txt (line 12))
  Downloading http://pypi.doubanio.com/packages/80/ad/cc2b0becd98050eed775ca85d6e5fa784547acff69f968183098df8a52b3/Flask-BabelEx-0.9.3.tar.gz (41kB)
Collecting pymysql (from -r requirements.txt (line 13))
  Downloading http://pypi.doubanio.com/packages/ed/39/15045ae46f2a123019aa968dfcba0396c161c20f855f11dea6796bcaae95/PyMySQL-0.9.3-py2.py3-none-any.whl (47kB)
Collecting psycopg2 (from -r requirements.txt (line 14))
  Downloading http://pypi.doubanio.com/packages/84/d7/6a93c99b5ba4d4d22daa3928b983cec66df4536ca50b22ce5dcac65e4e71/psycopg2-2.8.4.tar.gz (377kB)
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/psycopg2.egg-info
    writing pip-egg-info/psycopg2.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/psycopg2.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/psycopg2.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt'
    
    Error: pg_config executable not found.
    
    pg_config is required to build psycopg2 from source.  Please add the directory
    containing pg_config to the $PATH or specify the full executable path with the
    option:
    
        python setup.py build_ext --pg-config /path/to/pg_config build ...
    
    or with the pg_config option in 'setup.cfg'.
    
    If you prefer to avoid building psycopg2 from source, please install the PyPI
    'psycopg2-binary' package instead.
    
    For further information please check the 'doc/src/install.rst' file (also at
    <http://initd.org/psycopg/docs/install.html>).
    
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-sg4cklnw/psycopg2/
The command '/bin/sh -c pip3.6 install -r requirements.txt --timeout=120' returned a non-zero code: 1
`

**Comment by CodingCrush** [comment]
已修好，pyscopg安装的依赖和之前有变化
